-- ============================================================
-- CampusOne (UAMS) 샘플 데이터 INSERT 스크립트
-- ============================================================
--
-- ▶ 실행 환경
--   Oracle 21c XE | Service: XEPDB1 | Schema: UAMS
--   DataInitializer가 먼저 실행되어 admin(ID=1) 계정이 존재해야 합니다.
--
-- ▶ 실행 순서 (FK 의존성 순)
--   1. COLLEGES
--   2. ADMINISTRATIVE_OFFICES
--   3. (JOB_POSITIONS — DDL 스크립트에서 이미 삽입됨)
--   4. USERS (STAFF)
--   5. USERS (PROFESSOR)
--   6. USERS (STUDENT)
--   7. DEPARTMENTS (HEAD_PROFESSOR_ID 없이)
--   8. PROFESSORS
--   9. UPDATE DEPARTMENTS.HEAD_PROFESSOR_ID
--  10. STUDENTS
--  11. STAFF_MEMBERS
--  12. STAFF_JOBS
--  13. STAFF_ASSIGNMENT_HISTORY
--  14. COURSES
--  15. COURSE_SCHEDULES
--  16. ENROLLMENTS
--  17. GRADES
--  18. NOTICES
--  19. APPROVAL_TEMPLATES
--
-- ▶ 비밀번호 안내
--   관리자  : admin     / admin123  (DataInitializer 자동 생성)
--   나머지  : 각 USERNAME / test1234
--
--   PASSWORD_HASH 값은 BCryptPasswordEncoder(strength=10).encode("test1234")
--   결과입니다. 로그인이 안 될 경우 관리자 계정으로 접속 후
--   비밀번호 변경 API를 통해 재설정하세요.
--
-- ▶ 실행 방법
--   sqlplus UAMS/UamsPass123!@localhost:1521/XEPDB1 @data.sql
--   또는 DBeaver 등에서 UAMS 스키마 연결 후 전체 실행
-- ============================================================

-- 현재 세션 NLS 설정
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

-- 실행 중 에러가 있어도 계속 진행 (필요시 제거)
WHENEVER SQLERROR CONTINUE;

-- ============================================================
-- 0. BCrypt 해시 상수 정의
--    비밀번호: test1234
-- ============================================================
-- 아래 해시를 Oracle 세션 변수로 정의
-- (특수문자 포함으로 DEFINE 사용 불가 → 각 INSERT에 직접 사용)
-- $2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm


-- ============================================================
-- 1. 단과대학 (COLLEGES)
-- ============================================================

INSERT INTO COLLEGES (CODE, NAME) VALUES ('CE',  '공과대학');
INSERT INTO COLLEGES (CODE, NAME) VALUES ('NS',  '자연과학대학');
INSERT INTO COLLEGES (CODE, NAME) VALUES ('BIZ', '경영대학');
INSERT INTO COLLEGES (CODE, NAME) VALUES ('HUM', '인문대학');
INSERT INTO COLLEGES (CODE, NAME) VALUES ('SOC', '사회과학대학');
COMMIT;


-- ============================================================
-- 2. 행정 부서 (ADMINISTRATIVE_OFFICES)
-- ============================================================

INSERT INTO ADMINISTRATIVE_OFFICES (CODE, NAME, OFFICE_TYPE, LOCATION, PHONE)
VALUES ('ACADEMIC', '교학처', 'ACADEMIC', '본관 2층', '02-000-1100');

INSERT INTO ADMINISTRATIVE_OFFICES (CODE, NAME, OFFICE_TYPE, LOCATION, PHONE)
VALUES ('GENERAL', '총무처', 'GENERAL', '본관 1층', '02-000-1200');

INSERT INTO ADMINISTRATIVE_OFFICES (CODE, NAME, OFFICE_TYPE, LOCATION, PHONE)
VALUES ('IT_OFFICE', '전산실', 'IT', '공학관 B101', '02-000-1300');

INSERT INTO ADMINISTRATIVE_OFFICES (CODE, NAME, OFFICE_TYPE, LOCATION, PHONE)
VALUES ('LIBRARY', '도서관', 'LIBRARY', '도서관 1층', '02-000-1400');

INSERT INTO ADMINISTRATIVE_OFFICES (CODE, NAME, OFFICE_TYPE, LOCATION, PHONE)
VALUES ('STUDENT_AFFAIRS', '학생처', 'STUDENT_AFFAIRS', '학생회관 101호', '02-000-1500');

INSERT INTO ADMINISTRATIVE_OFFICES (CODE, NAME, OFFICE_TYPE, LOCATION, PHONE)
VALUES ('RESEARCH', '연구처', 'RESEARCH', '본관 3층', '02-000-1600');

INSERT INTO ADMINISTRATIVE_OFFICES (CODE, NAME, OFFICE_TYPE, LOCATION, PHONE)
VALUES ('FINANCE', '재무처', 'FINANCE', '본관 1층', '02-000-1700');
COMMIT;


-- ============================================================
-- 3. 직위 코드 (JOB_POSITIONS)
--    structure_v2_1.md DDL에 이미 포함되어 있음.
--    만약 DDL 스크립트에서 삽입되지 않은 경우 아래를 실행하세요.
-- ============================================================

-- MERGE INTO JOB_POSITIONS USING DUAL ON (CODE = 'DIRECTOR')
-- WHEN NOT MATCHED THEN INSERT (CODE, NAME, GRADE_LEVEL) VALUES ('DIRECTOR','처장',1);
-- (필요시 주석 해제 후 실행)


-- ============================================================
-- 4. 사용자 계정 (USERS) — 교직원 (STAFF) 3명
-- ============================================================
-- 비밀번호: test1234

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES (
    'staff_kim',
    '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
    '김교학', 'staff.kim@campus.ac.kr', '010-2001-0001', 'STAFF', 1
);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES (
    'staff_lee',
    '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
    '이총무', 'staff.lee@campus.ac.kr', '010-2001-0002', 'STAFF', 1
);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES (
    'staff_park',
    '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
    '박전산', 'staff.park@campus.ac.kr', '010-2001-0003', 'STAFF', 1
);
COMMIT;


-- ============================================================
-- 5. 사용자 계정 (USERS) — 교수 (PROFESSOR) 8명
-- ============================================================

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_cs1',  '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '이민준', 'prof.cs1@campus.ac.kr',  '010-3001-0001', 'PROFESSOR', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_cs2',  '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '김지수', 'prof.cs2@campus.ac.kr',  '010-3001-0002', 'PROFESSOR', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_ee',   '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '박준혁', 'prof.ee@campus.ac.kr',   '010-3001-0003', 'PROFESSOR', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_math', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '최수현', 'prof.math@campus.ac.kr', '010-3001-0004', 'PROFESSOR', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_phy',  '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '정도윤', 'prof.phy@campus.ac.kr',  '010-3001-0005', 'PROFESSOR', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_biz',  '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '윤서연', 'prof.biz@campus.ac.kr',  '010-3001-0006', 'PROFESSOR', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_eng',  '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '임지호', 'prof.eng@campus.ac.kr',  '010-3001-0007', 'PROFESSOR', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('prof_pol',  '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '한예은', 'prof.pol@campus.ac.kr',  '010-3001-0008', 'PROFESSOR', 1);
COMMIT;


-- ============================================================
-- 6. 사용자 계정 (USERS) — 학생 (STUDENT) 15명
-- ============================================================

-- 컴퓨터공학과 학생 5명
INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20210001', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '김민재', 's20210001@campus.ac.kr', '010-4001-0001', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20220001', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '이서윤', 's20220001@campus.ac.kr', '010-4001-0002', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20230001', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '박도현', 's20230001@campus.ac.kr', '010-4001-0003', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20240001', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '최예진', 's20240001@campus.ac.kr', '010-4001-0004', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20240002', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '정우진', 's20240002@campus.ac.kr', '010-4001-0005', 'STUDENT', 1);

-- 전기전자공학과 학생 3명
INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20210002', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '강하늘', 's20210002@campus.ac.kr', '010-4002-0001', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20230002', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '오지은', 's20230002@campus.ac.kr', '010-4002-0002', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20240003', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '임태양', 's20240003@campus.ac.kr', '010-4002-0003', 'STUDENT', 1);

-- 경영학과 학생 3명
INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20220002', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '윤채원', 's20220002@campus.ac.kr', '010-4003-0001', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20230003', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '한지민', 's20230003@campus.ac.kr', '010-4003-0002', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20240004', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '송민호', 's20240004@campus.ac.kr', '010-4003-0003', 'STUDENT', 1);

-- 수학과 학생 2명
INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20210003', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '배수아', 's20210003@campus.ac.kr', '010-4004-0001', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20230004', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '류준혁', 's20230004@campus.ac.kr', '010-4004-0002', 'STUDENT', 1);

-- 영어영문학과 학생 2명
INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20220003', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '노은서', 's20220003@campus.ac.kr', '010-4005-0001', 'STUDENT', 1);

INSERT INTO USERS (USERNAME, PASSWORD_HASH, NAME, EMAIL, PHONE, ROLE, IS_ACTIVE)
VALUES ('s20240005', '$2a$10$.SPiCWLA.e5fhlomJqo47.FegSTHErjjYih2uf5neF/9OPrt5ncDm',
        '마건우', 's20240005@campus.ac.kr', '010-4005-0002', 'STUDENT', 1);
COMMIT;


-- ============================================================
-- 7. 학과 (DEPARTMENTS) — HEAD_PROFESSOR_ID는 이후 UPDATE
-- ============================================================

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'CS', '컴퓨터공학과' FROM COLLEGES WHERE CODE = 'CE';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'EE', '전기전자공학과' FROM COLLEGES WHERE CODE = 'CE';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'ME', '기계공학과' FROM COLLEGES WHERE CODE = 'CE';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'MATH', '수학과' FROM COLLEGES WHERE CODE = 'NS';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'PHY', '물리학과' FROM COLLEGES WHERE CODE = 'NS';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'BIZ', '경영학과' FROM COLLEGES WHERE CODE = 'BIZ';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'ACC', '회계학과' FROM COLLEGES WHERE CODE = 'BIZ';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'ENG', '영어영문학과' FROM COLLEGES WHERE CODE = 'HUM';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'KOR', '국어국문학과' FROM COLLEGES WHERE CODE = 'HUM';

INSERT INTO DEPARTMENTS (COLLEGE_ID, CODE, NAME)
SELECT ID, 'POL', '정치외교학과' FROM COLLEGES WHERE CODE = 'SOC';
COMMIT;


-- ============================================================
-- 8. 교수 상세 (PROFESSORS)
-- ============================================================

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_cs1'),
    'P20200001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    '교수', '인공지능/기계학습', '공학관 301호', 'ACTIVE', DATE '2020-03-01'
);

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_cs2'),
    'P20180001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    '부교수', '소프트웨어공학/분산시스템', '공학관 302호', 'ACTIVE', DATE '2018-09-01'
);

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_ee'),
    'P20190001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'EE'),
    '교수', '전력전자/반도체', '공학관 201호', 'ACTIVE', DATE '2019-03-01'
);

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_math'),
    'P20150001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'MATH'),
    '교수', '해석학/위상수학', '자연과학관 101호', 'ACTIVE', DATE '2015-03-01'
);

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_phy'),
    'P20210001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'PHY'),
    '조교수', '양자역학/광학', '자연과학관 201호', 'ACTIVE', DATE '2021-09-01'
);

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_biz'),
    'P20160001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'BIZ'),
    '교수', '마케팅/소비자행동', '경영관 201호', 'ACTIVE', DATE '2016-03-01'
);

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_eng'),
    'P20170001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'ENG'),
    '교수', '영미문학/비교문학', '인문관 301호', 'ACTIVE', DATE '2017-03-01'
);

INSERT INTO PROFESSORS (USER_ID, PROFESSOR_NUMBER, DEPARTMENT_ID, POSITION, RESEARCH_FIELD, OFFICE_LOCATION, STATUS, HIRE_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_pol'),
    'P20220001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'POL'),
    '부교수', '국제정치/외교이론', '사회과학관 101호', 'ACTIVE', DATE '2022-03-01'
);
COMMIT;


-- ============================================================
-- 9. 학과장 업데이트 (HEAD_PROFESSOR_ID → USERS.ID)
-- ============================================================

UPDATE DEPARTMENTS
SET HEAD_PROFESSOR_ID = (SELECT ID FROM USERS WHERE USERNAME = 'prof_cs1')
WHERE CODE = 'CS';

UPDATE DEPARTMENTS
SET HEAD_PROFESSOR_ID = (SELECT ID FROM USERS WHERE USERNAME = 'prof_ee')
WHERE CODE = 'EE';

UPDATE DEPARTMENTS
SET HEAD_PROFESSOR_ID = (SELECT ID FROM USERS WHERE USERNAME = 'prof_math')
WHERE CODE = 'MATH';

UPDATE DEPARTMENTS
SET HEAD_PROFESSOR_ID = (SELECT ID FROM USERS WHERE USERNAME = 'prof_phy')
WHERE CODE = 'PHY';

UPDATE DEPARTMENTS
SET HEAD_PROFESSOR_ID = (SELECT ID FROM USERS WHERE USERNAME = 'prof_biz')
WHERE CODE = 'BIZ';

UPDATE DEPARTMENTS
SET HEAD_PROFESSOR_ID = (SELECT ID FROM USERS WHERE USERNAME = 'prof_eng')
WHERE CODE = 'ENG';

UPDATE DEPARTMENTS
SET HEAD_PROFESSOR_ID = (SELECT ID FROM USERS WHERE USERNAME = 'prof_pol')
WHERE CODE = 'POL';
COMMIT;


-- ============================================================
-- 10. 학생 상세 (STUDENTS)
-- ============================================================

-- 컴퓨터공학과 학생 5명
INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20210001'),
    '20210001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    4, 1, 2021, 'ENROLLED', DATE '2001-05-15', '서울특별시 관악구 신림동'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20220001'),
    '20220001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    3, 1, 2022, 'ENROLLED', DATE '2002-08-22', '경기도 수원시 팔달구'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20230001'),
    '20230001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    2, 1, 2023, 'ENROLLED', DATE '2004-03-11', '서울특별시 송파구 잠실동'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20240001'),
    '20240001',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    1, 1, 2024, 'ENROLLED', DATE '2005-07-30', '인천광역시 남동구'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20240002'),
    '20240002',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    1, 1, 2024, 'ENROLLED', DATE '2005-01-19', '경기도 성남시 분당구'
);

-- 전기전자공학과 학생 3명
INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20210002'),
    '20210002',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'EE'),
    4, 1, 2021, 'LEAVE', DATE '2001-11-03', '부산광역시 해운대구'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20230002'),
    '20230002',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'EE'),
    2, 1, 2023, 'ENROLLED', DATE '2003-09-25', '서울특별시 마포구 합정동'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20240003'),
    '20240003',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'EE'),
    1, 1, 2024, 'ENROLLED', DATE '2005-04-08', '대전광역시 유성구'
);

-- 경영학과 학생 3명
INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20220002'),
    '20220002',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'BIZ'),
    3, 1, 2022, 'ENROLLED', DATE '2002-12-17', '서울특별시 강남구 역삼동'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20230003'),
    '20230003',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'BIZ'),
    2, 1, 2023, 'ENROLLED', DATE '2003-06-02', '경기도 고양시 일산동구'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20240004'),
    '20240004',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'BIZ'),
    1, 1, 2024, 'ENROLLED', DATE '2004-10-28', '서울특별시 노원구 공릉동'
);

-- 수학과 학생 2명
INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20210003'),
    '20210003',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'MATH'),
    4, 1, 2021, 'GRADUATED', DATE '2001-02-14', '광주광역시 북구'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20230004'),
    '20230004',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'MATH'),
    2, 1, 2023, 'ENROLLED', DATE '2003-08-19', '울산광역시 남구'
);

-- 영어영문학과 학생 2명
INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20220003'),
    '20220003',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'ENG'),
    3, 1, 2022, 'ENROLLED', DATE '2002-03-30', '서울특별시 서대문구 신촌동'
);

INSERT INTO STUDENTS (USER_ID, STUDENT_NUMBER, DEPARTMENT_ID, GRADE, SEMESTER, ADMISSION_YEAR, STATUS, BIRTH_DATE, ADDRESS)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20240005'),
    '20240005',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'ENG'),
    1, 1, 2024, 'ENROLLED', DATE '2005-11-05', '경기도 용인시 기흥구'
);
COMMIT;


-- ============================================================
-- 11. 교직원 상세 (STAFF_MEMBERS)
-- ============================================================

INSERT INTO STAFF_MEMBERS (USER_ID, STAFF_NUMBER, OFFICE_ID, EMPLOYMENT_TYPE, STATUS, HIRE_DATE, OFFICE_PHONE, OFFICE_LOCATION, BIRTH_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_kim'),
    'S20180001',
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'ACADEMIC'),
    'FULL_TIME', 'ACTIVE', DATE '2018-03-01', '02-000-1101', '본관 201호', DATE '1985-04-12'
);

INSERT INTO STAFF_MEMBERS (USER_ID, STAFF_NUMBER, OFFICE_ID, EMPLOYMENT_TYPE, STATUS, HIRE_DATE, OFFICE_PHONE, OFFICE_LOCATION, BIRTH_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_lee'),
    'S20200001',
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'GENERAL'),
    'FULL_TIME', 'ACTIVE', DATE '2020-09-01', '02-000-1201', '본관 102호', DATE '1990-07-25'
);

INSERT INTO STAFF_MEMBERS (USER_ID, STAFF_NUMBER, OFFICE_ID, EMPLOYMENT_TYPE, STATUS, HIRE_DATE, OFFICE_PHONE, OFFICE_LOCATION, BIRTH_DATE)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_park'),
    'S20220001',
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'IT_OFFICE'),
    'FULL_TIME', 'ACTIVE', DATE '2022-03-01', '02-000-1301', '공학관 B102호', DATE '1993-01-18'
);
COMMIT;


-- ============================================================
-- 12. 교직원 직무 (STAFF_JOBS)
-- ============================================================

-- 교학처 김교학: 주직무(교학담당) + 겸직(CS학과담당)
INSERT INTO STAFF_JOBS (STAFF_MEMBER_ID, OFFICE_ID, POSITION_ID, DEPARTMENT_ID, JOB_TITLE, JOB_CATEGORY, IS_PRIMARY, START_DATE)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20180001'),
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'ACADEMIC'),
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'SENIOR'),
    NULL,
    '학사행정 총괄 담당', 'ACADEMIC', 1, DATE '2018-03-01'
);

INSERT INTO STAFF_JOBS (STAFF_MEMBER_ID, OFFICE_ID, POSITION_ID, DEPARTMENT_ID, JOB_TITLE, JOB_CATEGORY, IS_PRIMARY, START_DATE)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20180001'),
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'ACADEMIC'),
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'OFFICER'),
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    '컴퓨터공학과 학사 담당 (겸)', 'ACADEMIC', 0, DATE '2023-03-01'
);

-- 총무처 이총무: 주직무(인사담당)
INSERT INTO STAFF_JOBS (STAFF_MEMBER_ID, OFFICE_ID, POSITION_ID, DEPARTMENT_ID, JOB_TITLE, JOB_CATEGORY, IS_PRIMARY, START_DATE)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20200001'),
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'GENERAL'),
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'OFFICER'),
    NULL,
    '교직원 인사 및 급여 담당', 'HR', 1, DATE '2020-09-01'
);

-- 전산실 박전산: 주직무(시스템 관리)
INSERT INTO STAFF_JOBS (STAFF_MEMBER_ID, OFFICE_ID, POSITION_ID, DEPARTMENT_ID, JOB_TITLE, JOB_CATEGORY, IS_PRIMARY, START_DATE)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20220001'),
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'IT_OFFICE'),
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'OFFICER'),
    NULL,
    '학사정보시스템 운영 및 유지보수', 'IT', 1, DATE '2022-03-01'
);
COMMIT;


-- ============================================================
-- 13. 교직원 발령 이력 (STAFF_ASSIGNMENT_HISTORY)
-- ============================================================

-- 김교학: 신규 채용
INSERT INTO STAFF_ASSIGNMENT_HISTORY
    (STAFF_MEMBER_ID, FROM_OFFICE_ID, TO_OFFICE_ID, FROM_POSITION_ID, TO_POSITION_ID, ASSIGNMENT_TYPE, EFFECTIVE_DATE, REASON, PROCESSED_BY)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20180001'),
    NULL,
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'ACADEMIC'),
    NULL,
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'OFFICER'),
    'HIRE', DATE '2018-03-01', '신규 채용 (공개채용 2기)',
    (SELECT ID FROM USERS WHERE USERNAME = 'admin')
);

-- 김교학: 승진 (담당 → 주임)
INSERT INTO STAFF_ASSIGNMENT_HISTORY
    (STAFF_MEMBER_ID, FROM_OFFICE_ID, TO_OFFICE_ID, FROM_POSITION_ID, TO_POSITION_ID, ASSIGNMENT_TYPE, EFFECTIVE_DATE, REASON, PROCESSED_BY)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20180001'),
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'ACADEMIC'),
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'ACADEMIC'),
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'OFFICER'),
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'SENIOR'),
    'PROMOTION', DATE '2022-01-01', '2021년도 근무평가 우수 (S등급)',
    (SELECT ID FROM USERS WHERE USERNAME = 'admin')
);

-- 이총무: 신규 채용
INSERT INTO STAFF_ASSIGNMENT_HISTORY
    (STAFF_MEMBER_ID, FROM_OFFICE_ID, TO_OFFICE_ID, FROM_POSITION_ID, TO_POSITION_ID, ASSIGNMENT_TYPE, EFFECTIVE_DATE, REASON, PROCESSED_BY)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20200001'),
    NULL,
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'GENERAL'),
    NULL,
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'OFFICER'),
    'HIRE', DATE '2020-09-01', '신규 채용 (경력직)',
    (SELECT ID FROM USERS WHERE USERNAME = 'admin')
);

-- 박전산: 신규 채용
INSERT INTO STAFF_ASSIGNMENT_HISTORY
    (STAFF_MEMBER_ID, FROM_OFFICE_ID, TO_OFFICE_ID, FROM_POSITION_ID, TO_POSITION_ID, ASSIGNMENT_TYPE, EFFECTIVE_DATE, REASON, PROCESSED_BY)
VALUES (
    (SELECT ID FROM STAFF_MEMBERS WHERE STAFF_NUMBER = 'S20220001'),
    NULL,
    (SELECT ID FROM ADMINISTRATIVE_OFFICES WHERE CODE = 'IT_OFFICE'),
    NULL,
    (SELECT ID FROM JOB_POSITIONS WHERE CODE = 'OFFICER'),
    'HIRE', DATE '2022-03-01', '신규 채용 (공개채용 5기)',
    (SELECT ID FROM USERS WHERE USERNAME = 'admin')
);
COMMIT;


-- ============================================================
-- 14. 강의 (COURSES) — 2025년 1학기
-- ============================================================

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'CS101',
    '프로그래밍 기초',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_cs1'),
    3, 2025, 1, 40, 0, '공학관 201호', 'MAJOR',
    'Python을 이용한 프로그래밍 기초 개념 습득. 변수, 조건문, 반복문, 함수, 클래스를 다룬다.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'CS201',
    '자료구조',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_cs2'),
    3, 2025, 1, 35, 0, '공학관 202호', 'MAJOR',
    '배열, 연결리스트, 스택, 큐, 트리, 그래프 등 핵심 자료구조의 원리와 구현.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'CS301',
    '알고리즘',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_cs1'),
    3, 2025, 1, 30, 0, '공학관 203호', 'MAJOR',
    '정렬, 탐색, 동적 프로그래밍, 그래프 알고리즘 등 알고리즘 설계 및 분석.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'CS401',
    '데이터베이스',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_cs2'),
    3, 2025, 1, 30, 0, '공학관 204호', 'MAJOR_ELECTIVE',
    ' 관계형 데이터베이스 설계, SQL, 정규화, 트랜잭션 처리. Oracle/PostgreSQL 실습.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'EE101',
    '회로이론',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'EE'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_ee'),
    3, 2025, 1, 35, 0, '공학관 101호', 'MAJOR',
    'DC/AC 회로 해석, 키르히호프 법칙, 페이저 해석, 라플라스 변환 적용.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'MATH101',
    '미적분학',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'MATH'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_math'),
    3, 2025, 1, 60, 0, '자연과학관 101호', 'GENERAL_REQUIRED',
    '극한, 미분, 적분의 기초 개념과 응용. 다변수 함수까지 다룬다.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'PHY101',
    '일반물리학',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'PHY'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_phy'),
    3, 2025, 1, 50, 0, '자연과학관 201호', 'GENERAL_REQUIRED',
    '역학, 열역학, 전자기학, 광학의 기초 개념. 공학계열 필수 교양.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'BIZ101',
    '경영학원론',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'BIZ'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_biz'),
    3, 2025, 1, 50, 0, '경영관 101호', 'MAJOR',
    '경영의 기능(계획, 조직, 지휘, 통제), 경영환경, 기업의 사회적 책임 이해.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'ENG101',
    '영미문학개론',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'ENG'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_eng'),
    3, 2025, 1, 40, 0, '인문관 101호', 'MAJOR',
    '영미 소설, 시, 희곡의 주요 작품을 통해 영문학 전반을 개관한다.'
);

INSERT INTO COURSES (COURSE_CODE, NAME, DEPARTMENT_ID, PROFESSOR_ID, CREDIT, YEAR, SEMESTER, MAX_ENROLLMENT, CURRENT_ENROLLMENT, CLASSROOM, COURSE_TYPE, DESCRIPTION)
VALUES (
    'POL101',
    '정치학개론',
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'POL'),
    (SELECT P.ID FROM PROFESSORS P JOIN USERS U ON P.USER_ID = U.ID WHERE U.USERNAME = 'prof_pol'),
    3, 2025, 1, 45, 0, '사회과학관 101호', 'MAJOR',
    '정치의 개념, 권력, 국가, 민주주의, 선거제도, 국제정치의 기초 이해.'
);
COMMIT;


-- ============================================================
-- 15. 강의 시간표 (COURSE_SCHEDULES)
--     DAY_OF_WEEK: 1=월, 2=화, 3=수, 4=목, 5=금
--     PERIOD: 1교시=9시, 2교시=10시 ...
-- ============================================================

-- CS101 프로그래밍 기초: 월(1-2교시), 수(1-2교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS101'), 1, 1, 2, '공학관 201호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS101'), 3, 1, 2, '공학관 201호');

-- CS201 자료구조: 화(3-4교시), 목(3-4교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS201'), 2, 3, 4, '공학관 202호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS201'), 4, 3, 4, '공학관 202호');

-- CS301 알고리즘: 월(3-4교시), 수(3교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS301'), 1, 3, 4, '공학관 203호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS301'), 3, 3, 3, '공학관 203호');

-- CS401 데이터베이스: 화(1-2교시), 금(1-2교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS401'), 2, 1, 2, '공학관 204호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS401'), 5, 1, 2, '공학관 204호');

-- EE101 회로이론: 화(5-6교시), 목(5-6교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'EE101'), 2, 5, 6, '공학관 101호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'EE101'), 4, 5, 6, '공학관 101호');

-- MATH101 미적분학: 월(5-6교시), 수(5-6교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'), 1, 5, 6, '자연과학관 101호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'), 3, 5, 6, '자연과학관 101호');

-- PHY101 일반물리학: 화(1-2교시), 금(3-4교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'PHY101'), 2, 1, 2, '자연과학관 201호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'PHY101'), 5, 3, 4, '자연과학관 201호');

-- BIZ101 경영학원론: 수(1-2교시), 금(1-2교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'BIZ101'), 3, 1, 2, '경영관 101호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'BIZ101'), 5, 1, 2, '경영관 101호');

-- ENG101: 화(3-4교시), 목(3교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'ENG101'), 2, 3, 4, '인문관 101호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'ENG101'), 4, 3, 3, '인문관 101호');

-- POL101: 월(7-8교시), 수(7교시)
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'POL101'), 1, 7, 8, '사회과학관 101호');
INSERT INTO COURSE_SCHEDULES (COURSE_ID, DAY_OF_WEEK, PERIOD_START, PERIOD_END, CLASSROOM)
VALUES ((SELECT ID FROM COURSES WHERE COURSE_CODE = 'POL101'), 3, 7, 7, '사회과학관 101호');
COMMIT;


-- ============================================================
-- 16. 수강신청 (ENROLLMENTS) + CURRENT_ENROLLMENT 업데이트
--     CS 학생들이 여러 강의 수강신청
-- ============================================================

-- 김민재(s20210001, CS 4학년): CS301, CS401, MATH101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20210001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS301'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20210001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS401'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20210001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'),
    2025, 1, 'ENROLLED'
);

-- 이서윤(s20220001, CS 3학년): CS201, CS301, PHY101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20220001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS201'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20220001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS301'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20220001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'PHY101'),
    2025, 1, 'ENROLLED'
);

-- 박도현(s20230001, CS 2학년): CS101, CS201, MATH101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS201'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'),
    2025, 1, 'ENROLLED'
);

-- 최예진(s20240001, CS 1학년): CS101, MATH101, PHY101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'PHY101'),
    2025, 1, 'ENROLLED'
);

-- 정우진(s20240002, CS 1학년): CS101, CS201 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240002'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240002'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS201'),
    2025, 1, 'ENROLLED'
);

-- 오지은(s20230002, EE 2학년): EE101, MATH101, PHY101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230002'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'EE101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230002'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230002'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'PHY101'),
    2025, 1, 'ENROLLED'
);

-- 임태양(s20240003, EE 1학년): EE101, MATH101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240003'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'EE101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240003'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'),
    2025, 1, 'ENROLLED'
);

-- 윤채원(s20220002, BIZ 3학년): BIZ101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20220002'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'BIZ101'),
    2025, 1, 'ENROLLED'
);

-- 한지민(s20230003, BIZ 2학년): BIZ101, MATH101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230003'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'BIZ101'),
    2025, 1, 'ENROLLED'
);
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20230003'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'MATH101'),
    2025, 1, 'ENROLLED'
);

-- 노은서(s20220003, ENG 3학년): ENG101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20220003'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'ENG101'),
    2025, 1, 'ENROLLED'
);

-- 마건우(s20240005, ENG 1학년): ENG101 수강
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20240005'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'ENG101'),
    2025, 1, 'ENROLLED'
);

-- COURSES.CURRENT_ENROLLMENT 실제 수강자 수로 업데이트
UPDATE COURSES C
SET CURRENT_ENROLLMENT = (
    SELECT COUNT(*) FROM ENROLLMENTS E
    WHERE E.COURSE_ID = C.ID AND E.STATUS = 'ENROLLED'
);
COMMIT;


-- ============================================================
-- 17. 성적 (GRADES) — 이전 학기 완료 과목 일부 성적 입력
--     김민재(4학년) 지난 학기 성적 예시
-- ============================================================

-- 먼저 2024년 2학기 수강신청 데이터 (과거 학기) 삽입
INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20210001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS201'),
    2024, 2, 'COMPLETED'
);

INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20210001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    2024, 2, 'COMPLETED'
);

INSERT INTO ENROLLMENTS (STUDENT_ID, COURSE_ID, YEAR, SEMESTER, STATUS)
VALUES (
    (SELECT ID FROM STUDENTS WHERE STUDENT_NUMBER = '20220001'),
    (SELECT ID FROM COURSES WHERE COURSE_CODE = 'CS101'),
    2024, 2, 'COMPLETED'
);
COMMIT;

-- 성적 입력 (CONFIRMED 상태)
-- Oracle VALUES 절에서 JOIN 서브쿼리는 불안정하므로 INSERT INTO...SELECT 사용

-- 김민재 CS201 A+ (2024-2)
INSERT INTO GRADES (ENROLLMENT_ID, LETTER_GRADE, SCORE, GRADE_POINTS, IS_PASS_FAIL, STATUS, SUBMITTED_AT, CONFIRMED_AT, CONFIRMED_BY, REMARK)
SELECT
    E.ID,
    'A+', 98.5, 4.5, 0, 'CONFIRMED',
    SYSTIMESTAMP - INTERVAL '60' DAY,
    SYSTIMESTAMP - INTERVAL '50' DAY,
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_kim'),
    '우수한 성적, 발표 및 과제 모두 최고점'
FROM ENROLLMENTS E
JOIN STUDENTS S ON E.STUDENT_ID = S.ID
JOIN COURSES C ON E.COURSE_ID = C.ID
WHERE S.STUDENT_NUMBER = '20210001'
  AND C.COURSE_CODE = 'CS201'
  AND E.YEAR = 2024 AND E.SEMESTER = 2;

-- 김민재 CS101 A (2024-2)
INSERT INTO GRADES (ENROLLMENT_ID, LETTER_GRADE, SCORE, GRADE_POINTS, IS_PASS_FAIL, STATUS, SUBMITTED_AT, CONFIRMED_AT, CONFIRMED_BY)
SELECT
    E.ID,
    'A', 93.0, 4.0, 0, 'CONFIRMED',
    SYSTIMESTAMP - INTERVAL '60' DAY,
    SYSTIMESTAMP - INTERVAL '50' DAY,
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_kim')
FROM ENROLLMENTS E
JOIN STUDENTS S ON E.STUDENT_ID = S.ID
JOIN COURSES C ON E.COURSE_ID = C.ID
WHERE S.STUDENT_NUMBER = '20210001'
  AND C.COURSE_CODE = 'CS101'
  AND E.YEAR = 2024 AND E.SEMESTER = 2;

-- 이서윤 CS101 B+ (2024-2)
INSERT INTO GRADES (ENROLLMENT_ID, LETTER_GRADE, SCORE, GRADE_POINTS, IS_PASS_FAIL, STATUS, SUBMITTED_AT, CONFIRMED_AT, CONFIRMED_BY)
SELECT
    E.ID,
    'B+', 87.0, 3.5, 0, 'CONFIRMED',
    SYSTIMESTAMP - INTERVAL '60' DAY,
    SYSTIMESTAMP - INTERVAL '50' DAY,
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_kim')
FROM ENROLLMENTS E
JOIN STUDENTS S ON E.STUDENT_ID = S.ID
JOIN COURSES C ON E.COURSE_ID = C.ID
WHERE S.STUDENT_NUMBER = '20220001'
  AND C.COURSE_CODE = 'CS101'
  AND E.YEAR = 2024 AND E.SEMESTER = 2;
COMMIT;


-- ============================================================
-- 18. 공지사항 (NOTICES)
-- ============================================================

INSERT INTO NOTICES (TITLE, CONTENT, CATEGORY, AUTHOR_ID, IS_PINNED, VIEW_COUNT)
VALUES (
    '[필독] 2025학년도 1학기 수강신청 일정 안내',
    '2025학년도 1학기 수강신청 일정을 다음과 같이 안내합니다.

- 재학생 수강신청: 2025년 2월 17일(월) 09:00 ~ 2월 19일(수) 17:00
- 수강신청 변경기간: 2025년 2월 24일(월) 09:00 ~ 2월 25일(화) 17:00
- 개강일: 2025년 3월 3일(월)

수강 정원 초과 시 선착순으로 마감되오니 수강신청 시스템을 통해 정시에 신청하시기 바랍니다.
문의: 교학처 (02-000-1100)',
    'ACADEMIC',
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_kim'),
    1, 342
);

INSERT INTO NOTICES (TITLE, CONTENT, CATEGORY, AUTHOR_ID, DEPARTMENT_ID, IS_PINNED, VIEW_COUNT)
VALUES (
    '[컴퓨터공학과] 2025년 1학기 졸업논문 신청 안내',
    '컴퓨터공학과 4학년 졸업 예정자를 대상으로 졸업논문 신청을 안내합니다.

신청 자격: 졸업 예정자 (졸업학점 이수 예정자 포함)
신청 기간: 2025년 3월 10일(월) ~ 3월 14일(금)
신청 방법: 학사정보시스템 → 졸업논문신청 메뉴
지도교수 배정: 3월 21일(금) 이후 개별 통보

기타 문의사항은 컴퓨터공학과 학과사무실로 연락주시기 바랍니다.',
    'DEPARTMENT',
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_cs1'),
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    0, 178
);

INSERT INTO NOTICES (TITLE, CONTENT, CATEGORY, AUTHOR_ID, IS_PINNED, VIEW_COUNT)
VALUES (
    '2025년 전국 대학생 프로그래밍 경진대회 참가 안내',
    '전국 대학생 프로그래밍 경진대회(KUPC 2025) 참가자를 모집합니다.

- 대회 일시: 2025년 4월 12일(토) 10:00 ~ 17:00
- 참가 자격: 전국 4년제 대학 재학생
- 참가비: 무료
- 신청 마감: 2025년 3월 28일(금)
- 신청 방법: 대회 공식 홈페이지 접수

입상자에게는 상금 및 취업 연계 혜택이 제공됩니다.',
    'GENERAL',
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_kim'),
    0, 95
);

INSERT INTO NOTICES (TITLE, CONTENT, CATEGORY, AUTHOR_ID, IS_PINNED, VIEW_COUNT)
VALUES (
    '[학사] 2025학년도 1학기 휴학 신청 기간 안내',
    '2025학년도 1학기 휴학 신청 기간을 안내합니다.

■ 일반 휴학
- 신청 기간: 2025년 3월 3일(월) ~ 3월 28일(금)
- 신청 방법: 전자결재 시스템 → 휴학원 양식 작성
- 승인 절차: 지도교수 → 학과장 → 교학처장

■ 군 휴학
- 입영 예정일 1개월 전부터 신청 가능
- 증빙서류: 입영통지서 첨부 필수

자세한 사항은 학생처(02-000-1500)로 문의하세요.',
    'ACADEMIC',
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_lee'),
    0, 203
);

INSERT INTO NOTICES (TITLE, CONTENT, CATEGORY, AUTHOR_ID, DEPARTMENT_ID, IS_PINNED, VIEW_COUNT)
VALUES (
    '[CS401 데이터베이스] 1주차 강의 보충자료 공지',
    '안녕하세요, 데이터베이스 수업 담당 김지수 교수입니다.

1주차 강의에서 다룬 관계형 데이터베이스 기초 개념 보충자료를 첨부합니다.
특히 ER 다이어그램 → 관계형 스키마 변환 부분을 복습하시기 바랍니다.

다음 주 강의(2025.03.10)에는 SQL 기초 문법을 다룰 예정이며,
실습을 위해 Oracle SQL Developer 또는 DBeaver를 미리 설치해 오시기 바랍니다.

질문은 LMS 게시판 또는 오피스아워(화요일 14:00~16:00, 공학관 302호)를 이용해 주세요.',
    'COURSE',
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_cs2'),
    (SELECT ID FROM DEPARTMENTS WHERE CODE = 'CS'),
    0, 67
);

INSERT INTO NOTICES (TITLE, CONTENT, CATEGORY, AUTHOR_ID, IS_PINNED, VIEW_COUNT)
VALUES (
    '[공지] 학생증 재발급 및 모바일 학생증 전환 안내',
    '학생증 재발급 및 모바일 학생증 서비스 전환에 대해 안내드립니다.

■ 모바일 학생증
- 2025년 3월부터 모바일 학생증 서비스를 시작합니다.
- 기존 실물 학생증과 동일한 기능 제공 (도서관 출입, 학내 식당 할인 등)
- 발급 방법: CampusOne 앱 → 학생증 발급 메뉴

■ 실물 학생증 재발급
- 신청 기간: 연중 상시
- 신청 방법: 학생처 방문 또는 온라인 신청
- 수수료: 5,000원 (분실의 경우)

문의: 학생처 (02-000-1500)',
    'GENERAL',
    (SELECT ID FROM USERS WHERE USERNAME = 'staff_lee'),
    0, 412
);
COMMIT;


-- ============================================================
-- 19. 결재 양식 (APPROVAL_TEMPLATES)
-- ============================================================

INSERT INTO APPROVAL_TEMPLATES (CODE, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (
    'LEAVE_REQUEST',
    '휴학원',
    '재학생이 학기 중 또는 학기 전 휴학을 신청하는 문서입니다. 일반 휴학/군 휴학/질병 휴학 모두 이 양식을 사용합니다.',
    1
);

INSERT INTO APPROVAL_TEMPLATES (CODE, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (
    'RETURN_REQUEST',
    '복학원',
    '휴학 중인 학생이 복학을 신청하는 문서입니다.',
    1
);

INSERT INTO APPROVAL_TEMPLATES (CODE, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (
    'COURSE_CHANGE_REQUEST',
    '수강변경신청서',
    '수강신청 변경 기간 외에 수강 추가/취소를 요청하는 문서입니다. 학과장 및 담당 교수의 승인이 필요합니다.',
    1
);

INSERT INTO APPROVAL_TEMPLATES (CODE, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (
    'GRADE_OBJECTION',
    '성적이의신청서',
    '최종 성적에 이의가 있는 경우 담당 교수에게 재검토를 요청하는 문서입니다.',
    1
);

INSERT INTO APPROVAL_TEMPLATES (CODE, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (
    'STAFF_TRANSFER',
    '교직원 전보 발령',
    '교직원의 부서 전보를 처리하는 발령 문서입니다. 인사위원회 심의 후 총장 결재가 필요합니다.',
    1
);

INSERT INTO APPROVAL_TEMPLATES (CODE, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (
    'BUDGET_REQUEST',
    '예산집행품의서',
    '학과 또는 부서의 예산 집행을 요청하는 문서입니다.',
    1
);
COMMIT;


-- ============================================================
-- 20. 결재 문서 예시 (APPROVAL_DOCUMENTS + APPROVAL_LINES)
--     김민재(4학년)의 휴학원 기안 예시
-- ============================================================

INSERT INTO APPROVAL_DOCUMENTS (TEMPLATE_ID, TITLE, DRAFTER_ID, CONTENT, STATUS, CURRENT_STEP, SUBMITTED_AT)
VALUES (
    (SELECT ID FROM APPROVAL_TEMPLATES WHERE CODE = 'LEAVE_REQUEST'),
    '2025-1학기 일반 휴학 신청 - 김민재',
    (SELECT ID FROM USERS WHERE USERNAME = 's20210001'),
    '안녕하세요. 컴퓨터공학과 20210001 김민재입니다.

개인 사정으로 인해 2025학년도 1학기 휴학을 신청합니다.

휴학 사유: 건강 문제 (담당 의사 소견서 첨부)
휴학 기간: 2025년 3월 ~ 2025년 8월 (1학기)
복학 예정: 2025년 9월 (2학기)

지도교수님과 학과장님의 승인을 부탁드립니다.',
    'IN_PROGRESS', 1,
    SYSTIMESTAMP - INTERVAL '2' DAY
);

-- 결재선: 1단계(지도교수 이민준) → 2단계(교학처 김교학)
-- COMMENT는 Oracle 예약어이므로 반드시 "COMMENT"로 인용 처리

-- 1단계: 지도교수 (대기 중)
INSERT INTO APPROVAL_LINES (DOCUMENT_ID, STEP, APPROVER_ID, ROLE_LABEL, ACTION, "COMMENT", ACTION_AT)
SELECT D.ID, 1, U.ID, '지도교수', NULL, NULL, NULL
FROM APPROVAL_DOCUMENTS D
CROSS JOIN USERS U
WHERE D.TITLE = '2025-1학기 일반 휴학 신청 - 김민재'
  AND U.USERNAME = 'prof_cs1';

-- 2단계: 교학처 담당 (대기 중)
INSERT INTO APPROVAL_LINES (DOCUMENT_ID, STEP, APPROVER_ID, ROLE_LABEL, ACTION, "COMMENT", ACTION_AT)
SELECT D.ID, 2, U.ID, '교학처 담당자', NULL, NULL, NULL
FROM APPROVAL_DOCUMENTS D
CROSS JOIN USERS U
WHERE D.TITLE = '2025-1학기 일반 휴학 신청 - 김민재'
  AND U.USERNAME = 'staff_kim';

-- 알림: 지도교수에게 결재 요청 알림
INSERT INTO APPROVAL_NOTIFICATIONS (USER_ID, DOCUMENT_ID, MESSAGE, IS_READ)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 'prof_cs1'),
    (SELECT ID FROM APPROVAL_DOCUMENTS WHERE TITLE = '2025-1학기 일반 휴학 신청 - 김민재'),
    '[결재 요청] 김민재 학생의 휴학원 결재를 기다리고 있습니다.',
    0
);


-- 이서윤(3학년)의 성적이의신청서 (완료된 결재)
INSERT INTO APPROVAL_DOCUMENTS (TEMPLATE_ID, TITLE, DRAFTER_ID, CONTENT, STATUS, CURRENT_STEP, SUBMITTED_AT, COMPLETED_AT)
VALUES (
    (SELECT ID FROM APPROVAL_TEMPLATES WHERE CODE = 'GRADE_OBJECTION'),
    '2024-2학기 CS101 성적 이의신청 - 이서윤',
    (SELECT ID FROM USERS WHERE USERNAME = 's20220001'),
    '2024학년도 2학기 프로그래밍 기초(CS101) 최종 성적에 대해 이의를 신청합니다.

제출한 최종 과제에 오류가 있어 0점 처리된 것으로 확인되었으나,
과제 제출 이력(LMS 기록)을 확인하면 기한 내 제출이 완료되었습니다.

첨부: LMS 제출 완료 캡처 이미지

재검토를 부탁드립니다.',
    'APPROVED', 1,
    SYSTIMESTAMP - INTERVAL '45' DAY,
    SYSTIMESTAMP - INTERVAL '40' DAY
);

-- 1단계: 담당 교수 (승인 완료)
INSERT INTO APPROVAL_LINES (DOCUMENT_ID, STEP, APPROVER_ID, ROLE_LABEL, ACTION, "COMMENT", ACTION_AT)
SELECT D.ID, 1, U.ID,
       '담당 교수', 'APPROVED',
       '제출 이력 확인 완료. 과제 재채점 후 B+ → A 로 정정 처리함.',
       SYSTIMESTAMP - INTERVAL '40' DAY
FROM APPROVAL_DOCUMENTS D
CROSS JOIN USERS U
WHERE D.TITLE = '2024-2학기 CS101 성적 이의신청 - 이서윤'
  AND U.USERNAME = 'prof_cs2';

INSERT INTO APPROVAL_NOTIFICATIONS (USER_ID, DOCUMENT_ID, MESSAGE, IS_READ)
VALUES (
    (SELECT ID FROM USERS WHERE USERNAME = 's20220001'),
    (SELECT ID FROM APPROVAL_DOCUMENTS WHERE TITLE = '2024-2학기 CS101 성적 이의신청 - 이서윤'),
    '[결재 완료] 성적 이의신청이 승인되었습니다.',
    1
);
COMMIT;


-- ============================================================
-- 완료 메시지
-- ============================================================
-- 샘플 데이터 삽입이 완료되었습니다.
--
-- 삽입된 데이터 요약:
--   단과대학      : 5개 (공과/자연/경영/인문/사회)
--   행정부서      : 7개 (교학처/총무처/전산실/도서관/학생처/연구처/재무처)
--   학과          : 10개
--   교수 계정     : 8명 (prof_cs1 ~ prof_pol)
--   교직원 계정   : 3명 (staff_kim, staff_lee, staff_park)
--   학생 계정     : 15명 (s20210001 ~ s20240005)
--   강의          : 10개 (2025-1학기)
--   시간표        : 20개
--   수강신청      : 18건 (현재학기) + 3건 (과거학기)
--   성적          : 3건 (CONFIRMED)
--   공지사항      : 6건
--   결재양식      : 6종
--   결재문서      : 2건 (진행중 1, 완료 1)
--
-- 계정 정보:
--   admin     / admin123  (관리자 - DataInitializer 자동 생성)
--   staff_kim / test1234  (교학처 교직원)
--   staff_lee / test1234  (총무처 교직원)
--   staff_park/ test1234  (전산실 교직원)
--   prof_cs1  / test1234  (컴퓨터공학과 교수, 학과장)
--   prof_cs2  / test1234  (컴퓨터공학과 교수)
--   prof_ee   / test1234  (전기전자공학과 교수, 학과장)
--   prof_math / test1234  (수학과 교수, 학과장)
--   s20210001 / test1234  (CS 4학년 김민재)
--   s20220001 / test1234  (CS 3학년 이서윤)
--   s20240001 / test1234  (CS 1학년 최예진)
--   (나머지 학생도 동일하게 test1234)
-- ============================================================
