-- ============================================================
-- UAMS (University Academic Management System)
-- Oracle 21c XE — 전체 테이블 생성 스크립트
-- ============================================================
-- 실행 전: Oracle XEPDB1 에 UAMS 유저가 생성되어 있어야 합니다.
--   docker compose up -d  (infra/docker-compose.yml)
--
-- 실행 방법:
--   sql UAMS/UamsPass123!@localhost:1521/XEPDB1 @schema.sql
--   (또는 DBeaver 등 SQL 클라이언트에서 직접 실행)
--
-- 실행 순서: schema.sql → data.sql
-- ============================================================

-- ============================================================
-- 1. 인증 도메인
-- ============================================================

CREATE TABLE USERS (
    ID               NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME         VARCHAR2(50)    NOT NULL,
    PASSWORD_HASH    VARCHAR2(255)   NOT NULL,
    NAME             VARCHAR2(100)   NOT NULL,
    EMAIL            VARCHAR2(255)   NOT NULL,
    PHONE            VARCHAR2(20),
    ROLE             VARCHAR2(20)    NOT NULL,
    -- ADMIN | STAFF | PROFESSOR | STUDENT
    IS_ACTIVE        NUMBER(1,0)     DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    LOGIN_FAIL_COUNT NUMBER(3,0)     DEFAULT 0 NOT NULL,
    LOCKED_AT        TIMESTAMP WITH TIME ZONE,
    LAST_LOGIN_AT    TIMESTAMP WITH TIME ZONE,
    CREATED_BY       NUMBER(19),
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL    UNIQUE (EMAIL),
    CONSTRAINT CHK_USERS_ROLE CHECK (
        ROLE IN ('ADMIN','STAFF','PROFESSOR','STUDENT')
    )
);

CREATE INDEX IDX_USERS_ROLE   ON USERS(ROLE);
CREATE INDEX IDX_USERS_ACTIVE ON USERS(IS_ACTIVE, DELETED_AT);

COMMENT ON TABLE  USERS IS '통합 사용자 계정 (학생/교수/교직원/관리자)';
COMMENT ON COLUMN USERS.ROLE IS 'ADMIN=시스템관리자, STAFF=교직원, PROFESSOR=교수, STUDENT=학생';

-- --------------------------------------------------------

CREATE TABLE REFRESH_TOKENS (
    ID          NUMBER(19)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID     NUMBER(19)      NOT NULL,
    TOKEN       VARCHAR2(512)   NOT NULL,
    EXPIRES_AT  TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    REVOKED_AT  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_RT_USER  FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UK_RT_TOKEN UNIQUE (TOKEN)
);

CREATE INDEX IDX_RT_USER  ON REFRESH_TOKENS(USER_ID);
CREATE INDEX IDX_RT_TOKEN ON REFRESH_TOKENS(TOKEN);


-- ============================================================
-- 2. 조직 도메인
-- ============================================================

CREATE TABLE COLLEGES (
    ID         NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE       VARCHAR2(10)  NOT NULL,
    NAME       VARCHAR2(100) NOT NULL,
    CREATED_BY NUMBER(19),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UK_COLLEGES_CODE UNIQUE (CODE)
);

COMMENT ON TABLE COLLEGES IS '단과대학';

-- --------------------------------------------------------

CREATE TABLE DEPARTMENTS (
    ID                NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COLLEGE_ID        NUMBER(19)    NOT NULL,
    CODE              VARCHAR2(10)  NOT NULL,
    NAME              VARCHAR2(100) NOT NULL,
    HEAD_PROFESSOR_ID NUMBER(19),           -- 학과장 (PROFESSOR)
    CREATED_BY        NUMBER(19),
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_DEPT_COLLEGE   FOREIGN KEY (COLLEGE_ID)        REFERENCES COLLEGES(ID),
    CONSTRAINT FK_DEPT_HEAD_PROF FOREIGN KEY (HEAD_PROFESSOR_ID) REFERENCES USERS(ID),
    CONSTRAINT UK_DEPT_CODE      UNIQUE (CODE)
);

CREATE INDEX IDX_DEPT_COLLEGE ON DEPARTMENTS(COLLEGE_ID);

COMMENT ON TABLE DEPARTMENTS IS '학과';


-- ============================================================
-- 3. 학생 도메인
-- ============================================================

CREATE TABLE STUDENTS (
    ID             NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID        NUMBER(19)    NOT NULL,
    STUDENT_NUMBER VARCHAR2(20)  NOT NULL,   -- 예: 20240001
    DEPARTMENT_ID  NUMBER(19)    NOT NULL,
    GRADE          NUMBER(1,0)   NOT NULL,   -- 학년 1~4
    SEMESTER       NUMBER(1,0)   NOT NULL,   -- 학기 1~2
    ADMISSION_YEAR NUMBER(4,0)   NOT NULL,
    STATUS         VARCHAR2(20)  DEFAULT 'ENROLLED' NOT NULL,
    -- ENROLLED(재학) | LEAVE(휴학) | GRADUATED(졸업) | EXPELLED(제적)
    ADDRESS        VARCHAR2(500),
    BIRTH_DATE     DATE,
    CREATED_BY     NUMBER(19),
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_STU_USER   FOREIGN KEY (USER_ID)       REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_STU_DEPT   FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
    CONSTRAINT UK_STU_USER   UNIQUE (USER_ID),
    CONSTRAINT UK_STU_NUMBER UNIQUE (STUDENT_NUMBER),
    CONSTRAINT CHK_STU_GRADE    CHECK (GRADE    BETWEEN 1 AND 4),
    CONSTRAINT CHK_STU_SEMESTER CHECK (SEMESTER BETWEEN 1 AND 2),
    CONSTRAINT CHK_STU_STATUS   CHECK (STATUS IN ('ENROLLED','LEAVE','GRADUATED','EXPELLED'))
);

CREATE INDEX IDX_STU_DEPT   ON STUDENTS(DEPARTMENT_ID);
CREATE INDEX IDX_STU_STATUS ON STUDENTS(STATUS);

COMMENT ON TABLE  STUDENTS IS '학생 상세 정보 (USERS 1:1)';
COMMENT ON COLUMN STUDENTS.STATUS IS 'ENROLLED=재학, LEAVE=휴학, GRADUATED=졸업, EXPELLED=제적';


-- ============================================================
-- 4. 교수 도메인
-- ============================================================

CREATE TABLE PROFESSORS (
    ID               NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER(19)    NOT NULL,
    PROFESSOR_NUMBER VARCHAR2(20)  NOT NULL,   -- 예: P20240001
    DEPARTMENT_ID    NUMBER(19)    NOT NULL,
    POSITION         VARCHAR2(50),             -- 교수/부교수/조교수/강사
    RESEARCH_FIELD   VARCHAR2(200),
    OFFICE_LOCATION  VARCHAR2(100),
    OFFICE_PHONE     VARCHAR2(20),
    STATUS           VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    -- ACTIVE(재직) | LEAVE(휴직) | RETIRED(퇴직)
    HIRE_DATE        DATE,
    CREATED_BY       NUMBER(19),
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_PROF_USER  FOREIGN KEY (USER_ID)       REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROF_DEPT  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
    CONSTRAINT UK_PROF_USER  UNIQUE (USER_ID),
    CONSTRAINT UK_PROF_NUM   UNIQUE (PROFESSOR_NUMBER),
    CONSTRAINT CHK_PROF_STATUS CHECK (STATUS IN ('ACTIVE','LEAVE','RETIRED'))
);

CREATE INDEX IDX_PROF_DEPT ON PROFESSORS(DEPARTMENT_ID);

COMMENT ON TABLE PROFESSORS IS '교수 상세 정보 (USERS 1:1)';


-- ============================================================
-- 5. 교직원 도메인
-- ============================================================

CREATE TABLE ADMINISTRATIVE_OFFICES (
    ID          NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE        VARCHAR2(20)  NOT NULL,    -- 예: ACADEMIC, GENERAL, LIBRARY
    NAME        VARCHAR2(100) NOT NULL,
    PARENT_ID   NUMBER(19),               -- 상위 부서 (NULL=최상위)
    OFFICE_TYPE VARCHAR2(30)  NOT NULL,
    -- ACADEMIC | GENERAL | LIBRARY | STUDENT_AFFAIRS | RESEARCH | IT | FINANCE | PLANNING | ETC
    LOCATION    VARCHAR2(200),
    PHONE       VARCHAR2(30),
    CREATED_BY  NUMBER(19),
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_OFFICE_PARENT FOREIGN KEY (PARENT_ID) REFERENCES ADMINISTRATIVE_OFFICES(ID),
    CONSTRAINT UK_OFFICE_CODE   UNIQUE (CODE),
    CONSTRAINT CHK_OFFICE_TYPE  CHECK (
        OFFICE_TYPE IN (
            'ACADEMIC','GENERAL','LIBRARY','STUDENT_AFFAIRS',
            'RESEARCH','IT','FINANCE','PLANNING','ETC'
        )
    )
);

CREATE INDEX IDX_OFFICE_PARENT ON ADMINISTRATIVE_OFFICES(PARENT_ID);

COMMENT ON TABLE  ADMINISTRATIVE_OFFICES IS '행정 부서 (처/팀 단위)';
COMMENT ON COLUMN ADMINISTRATIVE_OFFICES.OFFICE_TYPE IS
    'ACADEMIC=교학처, GENERAL=총무처, IT=전산실, LIBRARY=도서관 등';

-- --------------------------------------------------------

CREATE TABLE JOB_POSITIONS (
    ID          NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE        VARCHAR2(30)  NOT NULL,    -- 예: DIRECTOR, TEAM_LEAD, OFFICER
    NAME        VARCHAR2(100) NOT NULL,   -- 예: 처장, 팀장, 담당자
    GRADE_LEVEL NUMBER(2,0),              -- 직급 레벨 (1=최고 ~ 9=최하)
    IS_ACTIVE   NUMBER(1,0)   DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_JOB_CODE UNIQUE (CODE)
);

COMMENT ON TABLE  JOB_POSITIONS IS '직위 코드 (처장/팀장/담당 등)';
COMMENT ON COLUMN JOB_POSITIONS.GRADE_LEVEL IS '1=처장급, 3=팀장급, 5=주임급, 7=담당자급';

-- 기본 직위 데이터
INSERT INTO JOB_POSITIONS (CODE, NAME, GRADE_LEVEL) VALUES ('DIRECTOR',    '처장',   1);
INSERT INTO JOB_POSITIONS (CODE, NAME, GRADE_LEVEL) VALUES ('DEPUTY_DIR',  '부처장', 2);
INSERT INTO JOB_POSITIONS (CODE, NAME, GRADE_LEVEL) VALUES ('TEAM_LEAD',   '팀장',   3);
INSERT INTO JOB_POSITIONS (CODE, NAME, GRADE_LEVEL) VALUES ('DEPUTY_LEAD', '부팀장', 4);
INSERT INTO JOB_POSITIONS (CODE, NAME, GRADE_LEVEL) VALUES ('SENIOR',      '주임',   5);
INSERT INTO JOB_POSITIONS (CODE, NAME, GRADE_LEVEL) VALUES ('OFFICER',     '담당자', 7);
INSERT INTO JOB_POSITIONS (CODE, NAME, GRADE_LEVEL) VALUES ('INTERN',      '인턴',   9);
COMMIT;

-- --------------------------------------------------------

CREATE TABLE STAFF_MEMBERS (
    ID               NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID          NUMBER(19)    NOT NULL,
    STAFF_NUMBER     VARCHAR2(20)  NOT NULL,    -- 사번 예: S20240001
    OFFICE_ID        NUMBER(19)    NOT NULL,    -- 주 소속 행정 부서
    EMPLOYMENT_TYPE  VARCHAR2(20)  DEFAULT 'FULL_TIME' NOT NULL,
    -- FULL_TIME(정규직) | PART_TIME(계약직) | INTERN(인턴)
    STATUS           VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    -- ACTIVE(재직) | LEAVE(휴직) | RETIRED(퇴직) | RESIGNED(의원면직)
    HIRE_DATE        DATE          NOT NULL,
    RETIRE_DATE      DATE,
    OFFICE_PHONE     VARCHAR2(30),
    OFFICE_LOCATION  VARCHAR2(200),
    BIRTH_DATE       DATE,
    ADDRESS          VARCHAR2(500),
    EMERGENCY_CONTACT VARCHAR2(100),
    CREATED_BY       NUMBER(19),
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_SM_USER   FOREIGN KEY (USER_ID)   REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SM_OFFICE FOREIGN KEY (OFFICE_ID) REFERENCES ADMINISTRATIVE_OFFICES(ID),
    CONSTRAINT UK_SM_USER   UNIQUE (USER_ID),
    CONSTRAINT UK_SM_NUMBER UNIQUE (STAFF_NUMBER),
    CONSTRAINT CHK_SM_EMP_TYPE CHECK (EMPLOYMENT_TYPE IN ('FULL_TIME','PART_TIME','INTERN')),
    CONSTRAINT CHK_SM_STATUS   CHECK (STATUS IN ('ACTIVE','LEAVE','RETIRED','RESIGNED'))
);

CREATE INDEX IDX_SM_OFFICE ON STAFF_MEMBERS(OFFICE_ID);
CREATE INDEX IDX_SM_STATUS ON STAFF_MEMBERS(STATUS);

COMMENT ON TABLE  STAFF_MEMBERS IS '교직원 상세 정보 (USERS 1:1)';
COMMENT ON COLUMN STAFF_MEMBERS.EMPLOYMENT_TYPE IS 'FULL_TIME=정규직, PART_TIME=계약직, INTERN=인턴';
COMMENT ON COLUMN STAFF_MEMBERS.STATUS IS 'ACTIVE=재직, LEAVE=휴직, RETIRED=퇴직, RESIGNED=의원면직';

-- --------------------------------------------------------

CREATE TABLE STAFF_JOBS (
    ID              NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STAFF_MEMBER_ID NUMBER(19)    NOT NULL,
    OFFICE_ID       NUMBER(19)    NOT NULL,    -- 해당 직무가 속한 행정 부서
    POSITION_ID     NUMBER(19)    NOT NULL,    -- 직위 (JOB_POSITIONS FK)
    DEPARTMENT_ID   NUMBER(19),               -- 학과 배속일 경우
    JOB_TITLE       VARCHAR2(200) NOT NULL,
    JOB_CATEGORY    VARCHAR2(30)  NOT NULL,
    -- ACADEMIC | HR | FINANCE | IT | LIBRARY | STUDENT_SUPPORT | RESEARCH_ADMIN | FACILITY | ETC
    IS_PRIMARY      NUMBER(1,0)   DEFAULT 1 NOT NULL CHECK (IS_PRIMARY IN (0,1)),
    -- 1=주 직무, 0=겸직
    START_DATE      DATE          NOT NULL,
    END_DATE        DATE,                      -- NULL=현재 수행 중
    DESCRIPTION     VARCHAR2(1000),
    CREATED_BY      NUMBER(19),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SJ_STAFF    FOREIGN KEY (STAFF_MEMBER_ID) REFERENCES STAFF_MEMBERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SJ_OFFICE   FOREIGN KEY (OFFICE_ID)       REFERENCES ADMINISTRATIVE_OFFICES(ID),
    CONSTRAINT FK_SJ_POSITION FOREIGN KEY (POSITION_ID)     REFERENCES JOB_POSITIONS(ID),
    CONSTRAINT FK_SJ_DEPT     FOREIGN KEY (DEPARTMENT_ID)   REFERENCES DEPARTMENTS(ID),
    CONSTRAINT CHK_SJ_CATEGORY CHECK (
        JOB_CATEGORY IN (
            'ACADEMIC','HR','FINANCE','IT','LIBRARY',
            'STUDENT_SUPPORT','RESEARCH_ADMIN','FACILITY','ETC'
        )
    )
);

CREATE INDEX IDX_SJ_STAFF    ON STAFF_JOBS(STAFF_MEMBER_ID);
CREATE INDEX IDX_SJ_OFFICE   ON STAFF_JOBS(OFFICE_ID);
CREATE INDEX IDX_SJ_DEPT     ON STAFF_JOBS(DEPARTMENT_ID);
CREATE INDEX IDX_SJ_ACTIVE   ON STAFF_JOBS(STAFF_MEMBER_ID, END_DATE);

COMMENT ON TABLE  STAFF_JOBS IS '교직원 직무 (1인 복수 직무·겸직 지원)';
COMMENT ON COLUMN STAFF_JOBS.IS_PRIMARY IS '1=주 직무, 0=겸직';
COMMENT ON COLUMN STAFF_JOBS.END_DATE   IS 'NULL이면 현재 수행 중인 직무';
COMMENT ON COLUMN STAFF_JOBS.JOB_CATEGORY IS
    'ACADEMIC=학사, HR=인사, FINANCE=재무, IT=전산, LIBRARY=도서관 등';

-- --------------------------------------------------------

CREATE TABLE STAFF_ASSIGNMENT_HISTORY (
    ID               NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STAFF_MEMBER_ID  NUMBER(19)    NOT NULL,
    FROM_OFFICE_ID   NUMBER(19),               -- 이전 부서 (첫 발령 시 NULL)
    TO_OFFICE_ID     NUMBER(19)    NOT NULL,
    FROM_POSITION_ID NUMBER(19),
    TO_POSITION_ID   NUMBER(19)    NOT NULL,
    ASSIGNMENT_TYPE  VARCHAR2(30)  NOT NULL,
    -- HIRE | TRANSFER | PROMOTION | DEMOTION | DISPATCH | RETURN | RETIRE | RESIGN
    EFFECTIVE_DATE   DATE          NOT NULL,
    REASON           VARCHAR2(500),
    PROCESSED_BY     NUMBER(19),               -- 처리자 (ADMIN/STAFF)
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SAH_STAFF       FOREIGN KEY (STAFF_MEMBER_ID)  REFERENCES STAFF_MEMBERS(ID),
    CONSTRAINT FK_SAH_FROM_OFFICE FOREIGN KEY (FROM_OFFICE_ID)   REFERENCES ADMINISTRATIVE_OFFICES(ID),
    CONSTRAINT FK_SAH_TO_OFFICE   FOREIGN KEY (TO_OFFICE_ID)     REFERENCES ADMINISTRATIVE_OFFICES(ID),
    CONSTRAINT FK_SAH_FROM_POS    FOREIGN KEY (FROM_POSITION_ID) REFERENCES JOB_POSITIONS(ID),
    CONSTRAINT FK_SAH_TO_POS      FOREIGN KEY (TO_POSITION_ID)   REFERENCES JOB_POSITIONS(ID),
    CONSTRAINT FK_SAH_PROCESSED   FOREIGN KEY (PROCESSED_BY)     REFERENCES USERS(ID),
    CONSTRAINT CHK_SAH_TYPE CHECK (
        ASSIGNMENT_TYPE IN (
            'HIRE','TRANSFER','PROMOTION','DEMOTION',
            'DISPATCH','RETURN','RETIRE','RESIGN'
        )
    )
);

CREATE INDEX IDX_SAH_STAFF ON STAFF_ASSIGNMENT_HISTORY(STAFF_MEMBER_ID);
CREATE INDEX IDX_SAH_DATE  ON STAFF_ASSIGNMENT_HISTORY(EFFECTIVE_DATE);

COMMENT ON TABLE STAFF_ASSIGNMENT_HISTORY IS '교직원 발령 이력 (전보/승진/퇴직 등)';


-- ============================================================
-- 6. 강의 도메인
-- ============================================================

CREATE TABLE COURSES (
    ID                 NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COURSE_CODE        VARCHAR2(20)  NOT NULL,
    NAME               VARCHAR2(200) NOT NULL,
    DEPARTMENT_ID      NUMBER(19)    NOT NULL,
    PROFESSOR_ID       NUMBER(19)    NOT NULL,
    CREDIT             NUMBER(1,0)   NOT NULL,
    YEAR               NUMBER(4,0)   NOT NULL,
    SEMESTER           NUMBER(1,0)   NOT NULL,
    MAX_ENROLLMENT     NUMBER(5,0)   DEFAULT 30 NOT NULL,
    CURRENT_ENROLLMENT NUMBER(5,0)   DEFAULT 0  NOT NULL,
    VERSION_NO         NUMBER(10,0)  DEFAULT 0  NOT NULL, -- 낙관적 락용
    CLASSROOM          VARCHAR2(100),
    COURSE_TYPE        VARCHAR2(30)  DEFAULT 'MAJOR' NOT NULL,
    -- MAJOR | MAJOR_ELECTIVE | GENERAL | GENERAL_REQUIRED
    DESCRIPTION        CLOB,
    STATUS             VARCHAR2(20)  DEFAULT 'OPEN' NOT NULL,
    -- OPEN | CLOSED | ENDED
    CREATED_BY         NUMBER(19),
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_CRS_DEPT  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
    CONSTRAINT FK_CRS_PROF  FOREIGN KEY (PROFESSOR_ID)  REFERENCES PROFESSORS(ID),
    CONSTRAINT UK_CRS_CODE  UNIQUE (COURSE_CODE),
    CONSTRAINT CHK_CRS_CREDIT   CHECK (CREDIT BETWEEN 1 AND 6),
    CONSTRAINT CHK_CRS_SEMESTER CHECK (SEMESTER IN (1, 2)),
    CONSTRAINT CHK_CRS_ENROLL   CHECK (CURRENT_ENROLLMENT <= MAX_ENROLLMENT),
    CONSTRAINT CHK_CRS_TYPE CHECK (
        COURSE_TYPE IN ('MAJOR','MAJOR_ELECTIVE','GENERAL','GENERAL_REQUIRED')
    ),
    CONSTRAINT CHK_CRS_STATUS CHECK (STATUS IN ('OPEN','CLOSED','ENDED'))
);

CREATE INDEX IDX_CRS_DEPT     ON COURSES(DEPARTMENT_ID);
CREATE INDEX IDX_CRS_PROF     ON COURSES(PROFESSOR_ID);
CREATE INDEX IDX_CRS_YEAR_SEM ON COURSES(YEAR, SEMESTER);

COMMENT ON COLUMN COURSES.VERSION_NO IS '낙관적 락 (@Version) 용 버전 컬럼';

-- --------------------------------------------------------

CREATE TABLE COURSE_SCHEDULES (
    ID           NUMBER(19)   GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COURSE_ID    NUMBER(19)   NOT NULL,
    DAY_OF_WEEK  NUMBER(1,0)  NOT NULL,   -- 1=월 ~ 6=토
    PERIOD_START NUMBER(2,0)  NOT NULL,
    PERIOD_END   NUMBER(2,0)  NOT NULL,
    CLASSROOM    VARCHAR2(100),
    CONSTRAINT FK_CS_COURSE    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_CS_DAY      CHECK (DAY_OF_WEEK  BETWEEN 1 AND 6),
    CONSTRAINT CHK_CS_PERIOD_S CHECK (PERIOD_START BETWEEN 1 AND 15),
    CONSTRAINT CHK_CS_PERIOD_E CHECK (PERIOD_END   BETWEEN 1 AND 15),
    CONSTRAINT CHK_CS_PERIOD   CHECK (PERIOD_START <= PERIOD_END)
);

CREATE INDEX IDX_CS_COURSE ON COURSE_SCHEDULES(COURSE_ID);


-- ============================================================
-- 7. 수강신청 도메인
-- ============================================================

CREATE TABLE ENROLLMENTS (
    ID           NUMBER(19)   GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STUDENT_ID   NUMBER(19)   NOT NULL,
    COURSE_ID    NUMBER(19)   NOT NULL,
    YEAR         NUMBER(4,0)  NOT NULL,
    SEMESTER     NUMBER(1,0)  NOT NULL,
    STATUS       VARCHAR2(20) DEFAULT 'ENROLLED' NOT NULL,
    -- ENROLLED | WITHDRAWN | COMPLETED
    ENROLLED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    WITHDRAWN_AT TIMESTAMP WITH TIME ZONE,
    CREATED_BY   NUMBER(19),
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ENR_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID),
    CONSTRAINT FK_ENR_COURSE  FOREIGN KEY (COURSE_ID)  REFERENCES COURSES(ID),
    CONSTRAINT UK_ENR_UNIQUE  UNIQUE (STUDENT_ID, COURSE_ID, YEAR, SEMESTER),
    CONSTRAINT CHK_ENR_SEM    CHECK (SEMESTER IN (1, 2)),
    CONSTRAINT CHK_ENR_STATUS CHECK (STATUS IN ('ENROLLED','WITHDRAWN','COMPLETED'))
);

CREATE INDEX IDX_ENR_STUDENT ON ENROLLMENTS(STUDENT_ID);
CREATE INDEX IDX_ENR_COURSE  ON ENROLLMENTS(COURSE_ID);


-- ============================================================
-- 8. 성적 도메인
-- ============================================================

CREATE TABLE GRADES (
    ID            NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ENROLLMENT_ID NUMBER(19)    NOT NULL,
    LETTER_GRADE  VARCHAR2(5),              -- A+, A, B+, B, C+, C, D+, D, F, P, NP
    SCORE         NUMBER(5,2),
    GRADE_POINTS  NUMBER(3,2),             -- 환산 평점 (4.5~0.0)
    IS_PASS_FAIL  NUMBER(1,0)  DEFAULT 0 NOT NULL CHECK (IS_PASS_FAIL IN (0,1)),
    STATUS        VARCHAR2(20) DEFAULT 'TEMP' NOT NULL,
    -- TEMP | SUBMITTED | CONFIRMED
    SUBMITTED_AT  TIMESTAMP WITH TIME ZONE,
    CONFIRMED_AT  TIMESTAMP WITH TIME ZONE,
    CONFIRMED_BY  NUMBER(19),
    REMARK        VARCHAR2(1000),
    CREATED_BY    NUMBER(19),
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_GRD_ENROLLMENT FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENTS(ID),
    CONSTRAINT FK_GRD_CONFIRMED  FOREIGN KEY (CONFIRMED_BY)  REFERENCES USERS(ID),
    CONSTRAINT UK_GRD_ENROLLMENT UNIQUE (ENROLLMENT_ID),
    CONSTRAINT CHK_GRD_LETTER CHECK (
        LETTER_GRADE IN ('A+','A','B+','B','C+','C','D+','D','F','P','NP')
    ),
    CONSTRAINT CHK_GRD_POINTS CHECK (GRADE_POINTS BETWEEN 0.0 AND 4.5),
    CONSTRAINT CHK_GRD_STATUS CHECK (STATUS IN ('TEMP','SUBMITTED','CONFIRMED'))
);

CREATE INDEX IDX_GRD_ENROLLMENT ON GRADES(ENROLLMENT_ID);
CREATE INDEX IDX_GRD_STATUS     ON GRADES(STATUS);


-- ============================================================
-- 9. 공지사항 도메인
-- ============================================================

CREATE TABLE NOTICES (
    ID            NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE         VARCHAR2(500) NOT NULL,
    CONTENT       CLOB          NOT NULL,
    CATEGORY      VARCHAR2(30)  DEFAULT 'GENERAL' NOT NULL,
    -- ACADEMIC | DEPARTMENT | COURSE | GENERAL
    AUTHOR_ID     NUMBER(19)    NOT NULL,
    DEPARTMENT_ID NUMBER(19),
    COURSE_ID     NUMBER(19),
    IS_PINNED     NUMBER(1,0)  DEFAULT 0 NOT NULL CHECK (IS_PINNED IN (0,1)),
    VIEW_COUNT    NUMBER(10,0) DEFAULT 0  NOT NULL,
    CREATED_BY    NUMBER(19),
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_NTC_AUTHOR FOREIGN KEY (AUTHOR_ID)     REFERENCES USERS(ID),
    CONSTRAINT FK_NTC_DEPT   FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
    CONSTRAINT FK_NTC_COURSE FOREIGN KEY (COURSE_ID)     REFERENCES COURSES(ID),
    CONSTRAINT CHK_NTC_CATEGORY CHECK (
        CATEGORY IN ('ACADEMIC','DEPARTMENT','COURSE','GENERAL')
    )
);

CREATE INDEX IDX_NTC_AUTHOR   ON NOTICES(AUTHOR_ID);
CREATE INDEX IDX_NTC_CATEGORY ON NOTICES(CATEGORY);
CREATE INDEX IDX_NTC_PINNED   ON NOTICES(IS_PINNED, CREATED_AT DESC);

-- --------------------------------------------------------

CREATE TABLE NOTICE_ATTACHMENTS (
    ID         NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOTICE_ID  NUMBER(19)    NOT NULL,
    FILE_NAME  VARCHAR2(255) NOT NULL,
    FILE_PATH  VARCHAR2(1000) NOT NULL,
    FILE_SIZE  NUMBER(15,0)  NOT NULL,
    MIME_TYPE  VARCHAR2(100),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_NA_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES NOTICES(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_NA_NOTICE ON NOTICE_ATTACHMENTS(NOTICE_ID);


-- ============================================================
-- 10. 전자결재 도메인
-- ============================================================

CREATE TABLE APPROVAL_TEMPLATES (
    ID            NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE          VARCHAR2(50)  NOT NULL,
    NAME          VARCHAR2(200) NOT NULL,
    DESCRIPTION   VARCHAR2(1000),
    FIELDS_SCHEMA CLOB CHECK (FIELDS_SCHEMA IS JSON),
    IS_ACTIVE     NUMBER(1,0)  DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    CREATED_BY    NUMBER(19),
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_AT_CODE UNIQUE (CODE)
);

-- --------------------------------------------------------

CREATE TABLE APPROVAL_DOCUMENTS (
    ID           NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEMPLATE_ID  NUMBER(19)    NOT NULL,
    TITLE        VARCHAR2(500) NOT NULL,
    DRAFTER_ID   NUMBER(19)    NOT NULL,
    CONTENT      CLOB          NOT NULL,
    FORM_DATA    CLOB CHECK (FORM_DATA IS JSON),
    STATUS       VARCHAR2(20)  DEFAULT 'DRAFT' NOT NULL,
    -- DRAFT | IN_PROGRESS | APPROVED | REJECTED
    CURRENT_STEP NUMBER(3,0)   DEFAULT 1 NOT NULL,
    SUBMITTED_AT TIMESTAMP WITH TIME ZONE,
    COMPLETED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_BY   NUMBER(19),
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_AD_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES APPROVAL_TEMPLATES(ID),
    CONSTRAINT FK_AD_DRAFTER  FOREIGN KEY (DRAFTER_ID)  REFERENCES USERS(ID),
    CONSTRAINT CHK_AD_STATUS  CHECK (STATUS IN ('DRAFT','IN_PROGRESS','APPROVED','REJECTED'))
);

CREATE INDEX IDX_AD_DRAFTER ON APPROVAL_DOCUMENTS(DRAFTER_ID);
CREATE INDEX IDX_AD_STATUS  ON APPROVAL_DOCUMENTS(STATUS);

-- --------------------------------------------------------

CREATE TABLE APPROVAL_LINES (
    ID          NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DOCUMENT_ID NUMBER(19)    NOT NULL,
    STEP        NUMBER(3,0)   NOT NULL,
    APPROVER_ID NUMBER(19)    NOT NULL,
    ROLE_LABEL  VARCHAR2(100),
    ACTION      VARCHAR2(20),            -- APPROVED | REJECTED | NULL(대기)
    "COMMENT"   VARCHAR2(2000),
    ACTION_AT   TIMESTAMP WITH TIME ZONE,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AL_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES APPROVAL_DOCUMENTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_AL_APPROVER FOREIGN KEY (APPROVER_ID) REFERENCES USERS(ID),
    CONSTRAINT UK_AL_STEP     UNIQUE (DOCUMENT_ID, STEP),
    CONSTRAINT CHK_AL_ACTION  CHECK (ACTION IN ('APPROVED','REJECTED') OR ACTION IS NULL)
);

CREATE INDEX IDX_AL_DOCUMENT ON APPROVAL_LINES(DOCUMENT_ID);
CREATE INDEX IDX_AL_APPROVER ON APPROVAL_LINES(APPROVER_ID);

-- --------------------------------------------------------

CREATE TABLE APPROVAL_NOTIFICATIONS (
    ID          NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID     NUMBER(19)    NOT NULL,
    DOCUMENT_ID NUMBER(19)    NOT NULL,
    MESSAGE     VARCHAR2(500) NOT NULL,
    IS_READ     NUMBER(1,0)  DEFAULT 0 NOT NULL CHECK (IS_READ IN (0,1)),
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AN_USER     FOREIGN KEY (USER_ID)     REFERENCES USERS(ID),
    CONSTRAINT FK_AN_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES APPROVAL_DOCUMENTS(ID)
);

CREATE INDEX IDX_AN_USER ON APPROVAL_NOTIFICATIONS(USER_ID, IS_READ);


-- ============================================================
-- 11. 출결 도메인
-- ============================================================

CREATE TABLE ATTENDANCE_SESSIONS (
    ID             NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COURSE_ID      NUMBER(19)    NOT NULL,
    PROFESSOR_ID   NUMBER(19)    NOT NULL,
    LECTURE_DATE   DATE          NOT NULL,
    START_TIME     TIMESTAMP WITH TIME ZONE NOT NULL,
    END_TIME       TIMESTAMP WITH TIME ZONE NOT NULL,
    LATE_THRESHOLD TIMESTAMP WITH TIME ZONE,            -- NULL이면 지각 미구분
    ACCESS_CODE    VARCHAR2(6)   NOT NULL,               -- 학생이 입력하는 6자리 숫자
    QR_TOKEN       VARCHAR2(64)  NOT NULL,               -- UUID, QR URL 경로에 사용
    STATUS         VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    -- ACTIVE | CLOSED | EXPIRED
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATTS_COURSE   FOREIGN KEY (COURSE_ID)    REFERENCES COURSES(ID),
    CONSTRAINT FK_ATTS_PROF     FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSORS(ID),
    CONSTRAINT UK_ATTS_QR_TOKEN UNIQUE (QR_TOKEN),
    CONSTRAINT CHK_ATTS_STATUS  CHECK (STATUS IN ('ACTIVE','CLOSED','EXPIRED'))
);

CREATE INDEX IDX_ATTS_COURSE ON ATTENDANCE_SESSIONS(COURSE_ID);
CREATE INDEX IDX_ATTS_DATE   ON ATTENDANCE_SESSIONS(LECTURE_DATE);
CREATE INDEX IDX_ATTS_STATUS ON ATTENDANCE_SESSIONS(STATUS);
CREATE INDEX IDX_ATTS_QR     ON ATTENDANCE_SESSIONS(QR_TOKEN);

COMMENT ON TABLE  ATTENDANCE_SESSIONS IS '강의 출결 세션 (교수가 강의별 출석 체크 시 생성)';
COMMENT ON COLUMN ATTENDANCE_SESSIONS.ACCESS_CODE    IS '학생이 입력하는 6자리 숫자 코드 (세션마다 재생성 가능)';
COMMENT ON COLUMN ATTENDANCE_SESSIONS.QR_TOKEN       IS 'QR코드 URL에 포함되는 UUID — 예측 불가능하게 생성';
COMMENT ON COLUMN ATTENDANCE_SESSIONS.LATE_THRESHOLD IS '이 시각 이후 체크인 시 LATE 처리. NULL이면 시간 내 PRESENT만';

-- --------------------------------------------------------

CREATE TABLE ATTENDANCE_RECORDS (
    ID            NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SESSION_ID    NUMBER(19)    NOT NULL,
    STUDENT_ID    NUMBER(19)    NOT NULL,
    STATUS        VARCHAR2(20)  DEFAULT 'PRESENT' NOT NULL,
    -- PRESENT | LATE | ABSENT
    CHECKED_IN_AT TIMESTAMP WITH TIME ZONE,
    LATITUDE      NUMBER(10,7),
    LONGITUDE     NUMBER(10,7),
    IS_MANUAL     NUMBER(1,0)   DEFAULT 0 NOT NULL CHECK (IS_MANUAL IN (0,1)),
    MANUAL_REASON VARCHAR2(500),
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATTR_SESSION     FOREIGN KEY (SESSION_ID) REFERENCES ATTENDANCE_SESSIONS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ATTR_STUDENT     FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID),
    CONSTRAINT UK_ATTR_SESSION_STU UNIQUE (SESSION_ID, STUDENT_ID),
    CONSTRAINT CHK_ATTR_STATUS     CHECK (STATUS IN ('PRESENT','LATE','ABSENT'))
);

CREATE INDEX IDX_ATTR_SESSION ON ATTENDANCE_RECORDS(SESSION_ID);
CREATE INDEX IDX_ATTR_STUDENT ON ATTENDANCE_RECORDS(STUDENT_ID);
CREATE INDEX IDX_ATTR_STATUS  ON ATTENDANCE_RECORDS(STATUS);

COMMENT ON TABLE  ATTENDANCE_RECORDS IS '학생 개인 출결 기록 (세션별 1인 1레코드)';
COMMENT ON COLUMN ATTENDANCE_RECORDS.STATUS        IS 'PRESENT=출석, LATE=지각, ABSENT=결석';
COMMENT ON COLUMN ATTENDANCE_RECORDS.IS_MANUAL     IS '1=교수·교직원 수동 처리, 0=학생 직접 체크인';
COMMENT ON COLUMN ATTENDANCE_RECORDS.MANUAL_REASON IS '수동 처리 사유 (예: 사전 결석계, 의료 사유 등)';


-- ============================================================
-- 12. 상담 도메인
-- ============================================================

CREATE TABLE COUNSELING_REQUESTS (
    ID              NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STUDENT_ID      NUMBER(19)    NOT NULL,
    COUNSELOR_ID    NUMBER(19),               -- 배정된 상담사 (NULL=미배정)
    COUNSELING_TYPE VARCHAR2(30)  NOT NULL,
    -- ACADEMIC | MENTAL | CAREER | FINANCIAL | PERSONAL | ETC
    PREFERRED_DATE  DATE,
    REASON          CLOB          NOT NULL,
    STATUS          VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    -- PENDING | ACCEPTED | REJECTED | COMPLETED | CANCELLED
    REJECT_REASON   VARCHAR2(500),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CR_STUDENT   FOREIGN KEY (STUDENT_ID)   REFERENCES STUDENTS(ID),
    CONSTRAINT FK_CR_COUNSELOR FOREIGN KEY (COUNSELOR_ID) REFERENCES USERS(ID),
    CONSTRAINT CHK_CR_TYPE   CHECK (COUNSELING_TYPE IN ('ACADEMIC','MENTAL','CAREER','FINANCIAL','PERSONAL','ETC')),
    CONSTRAINT CHK_CR_STATUS CHECK (STATUS IN ('PENDING','ACCEPTED','REJECTED','COMPLETED','CANCELLED'))
);

CREATE INDEX IDX_CR_STUDENT   ON COUNSELING_REQUESTS(STUDENT_ID);
CREATE INDEX IDX_CR_COUNSELOR ON COUNSELING_REQUESTS(COUNSELOR_ID);
CREATE INDEX IDX_CR_STATUS    ON COUNSELING_REQUESTS(STATUS);

COMMENT ON TABLE  COUNSELING_REQUESTS IS '학생 상담 신청 (학생이 직접 신청)';
COMMENT ON COLUMN COUNSELING_REQUESTS.STATUS      IS 'PENDING=접수, ACCEPTED=수락, REJECTED=거절, COMPLETED=완료, CANCELLED=취소';
COMMENT ON COLUMN COUNSELING_REQUESTS.COUNSELOR_ID IS 'NULL이면 미배정 상태. 수락 시 배정됨.';

-- --------------------------------------------------------

CREATE TABLE COUNSELING_RECORDS (
    ID              NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REQUEST_ID      NUMBER(19),               -- 신청서 연결 (직접 기록 시 NULL)
    STUDENT_ID      NUMBER(19)    NOT NULL,
    COUNSELOR_ID    NUMBER(19)    NOT NULL,
    COUNSELING_TYPE VARCHAR2(30)  NOT NULL,
    SUBJECT         VARCHAR2(500) NOT NULL,
    CONTENT         CLOB          NOT NULL,
    OUTCOME         CLOB,
    FOLLOW_UP       VARCHAR2(1000),
    COUNSELED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    IS_NOTIFIED     NUMBER(1,0)   DEFAULT 0 NOT NULL CHECK (IS_NOTIFIED IN (0,1)),
    IS_CONFIDENTIAL NUMBER(1,0)   DEFAULT 0 NOT NULL CHECK (IS_CONFIDENTIAL IN (0,1)),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CREC_REQUEST   FOREIGN KEY (REQUEST_ID)   REFERENCES COUNSELING_REQUESTS(ID),
    CONSTRAINT FK_CREC_STUDENT   FOREIGN KEY (STUDENT_ID)   REFERENCES STUDENTS(ID),
    CONSTRAINT FK_CREC_COUNSELOR FOREIGN KEY (COUNSELOR_ID) REFERENCES USERS(ID),
    CONSTRAINT CHK_CREC_TYPE CHECK (COUNSELING_TYPE IN ('ACADEMIC','MENTAL','CAREER','FINANCIAL','PERSONAL','ETC'))
);

CREATE INDEX IDX_CREC_STUDENT   ON COUNSELING_RECORDS(STUDENT_ID);
CREATE INDEX IDX_CREC_COUNSELOR ON COUNSELING_RECORDS(COUNSELOR_ID);
CREATE INDEX IDX_CREC_DATE      ON COUNSELING_RECORDS(COUNSELED_AT);

COMMENT ON TABLE  COUNSELING_RECORDS IS '상담 기록 (신청 연결 또는 직접 작성)';
COMMENT ON COLUMN COUNSELING_RECORDS.IS_CONFIDENTIAL IS '1=비밀 상담, 학생 측 조회 API에서 내용 숨김';
COMMENT ON COLUMN COUNSELING_RECORDS.IS_NOTIFIED     IS '1=이메일 발송 완료';


-- ============================================================
-- 13. 과제 도메인
-- ============================================================

CREATE TABLE ASSIGNMENTS (
    ID                NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COURSE_ID         NUMBER(19)    NOT NULL,
    PROFESSOR_ID      NUMBER(19)    NOT NULL,
    TITLE             VARCHAR2(500) NOT NULL,
    DESCRIPTION       CLOB,
    DUE_DATE          TIMESTAMP WITH TIME ZONE NOT NULL,
    MAX_SCORE         NUMBER(5,2)   DEFAULT 100 NOT NULL,
    ALLOW_LATE_SUBMIT NUMBER(1,0)   DEFAULT 0 NOT NULL CHECK (ALLOW_LATE_SUBMIT IN (0,1)),
    IS_VISIBLE        NUMBER(1,0)   DEFAULT 1 NOT NULL CHECK (IS_VISIBLE IN (0,1)),
    SUBMISSION_TYPE   VARCHAR2(20)  DEFAULT 'FILE' NOT NULL,
    -- FILE | TEXT | BOTH
    STATUS            VARCHAR2(20)  DEFAULT 'OPEN' NOT NULL,
    -- OPEN | CLOSED | GRADED
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ASSIGN_COURSE FOREIGN KEY (COURSE_ID)    REFERENCES COURSES(ID),
    CONSTRAINT FK_ASSIGN_PROF   FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSORS(ID),
    CONSTRAINT CHK_ASSIGN_SUB_TYPE CHECK (SUBMISSION_TYPE IN ('FILE','TEXT','BOTH')),
    CONSTRAINT CHK_ASSIGN_STATUS   CHECK (STATUS IN ('OPEN','CLOSED','GRADED'))
);

CREATE INDEX IDX_ASSIGN_COURSE ON ASSIGNMENTS(COURSE_ID);
CREATE INDEX IDX_ASSIGN_STATUS ON ASSIGNMENTS(STATUS);
CREATE INDEX IDX_ASSIGN_DUE    ON ASSIGNMENTS(DUE_DATE);

COMMENT ON TABLE  ASSIGNMENTS IS '강의별 과제 (교수가 강의 단위로 생성)';
COMMENT ON COLUMN ASSIGNMENTS.ALLOW_LATE_SUBMIT IS '1=지각 제출 허용, 0=마감 후 제출 차단';
COMMENT ON COLUMN ASSIGNMENTS.SUBMISSION_TYPE   IS 'FILE=파일업로드, TEXT=텍스트, BOTH=모두 허용';

-- --------------------------------------------------------

CREATE TABLE ASSIGNMENT_SUBMISSIONS (
    ID            NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ASSIGNMENT_ID NUMBER(19)    NOT NULL,
    STUDENT_ID    NUMBER(19)    NOT NULL,
    CONTENT       CLOB,
    FILE_NAME     VARCHAR2(255),
    FILE_PATH     VARCHAR2(1000),
    FILE_SIZE     NUMBER(15,0),
    STATUS        VARCHAR2(20)  DEFAULT 'SUBMITTED' NOT NULL,
    -- SUBMITTED | LATE | GRADED
    SCORE         NUMBER(5,2),
    FEEDBACK      CLOB,
    SUBMITTED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    GRADED_AT     TIMESTAMP WITH TIME ZONE,
    GRADED_BY     NUMBER(19),
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ASUB_ASSIGN  FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ASUB_STUDENT FOREIGN KEY (STUDENT_ID)   REFERENCES STUDENTS(ID),
    CONSTRAINT FK_ASUB_GRADER  FOREIGN KEY (GRADED_BY)    REFERENCES USERS(ID),
    CONSTRAINT UK_ASUB_UNIQUE  UNIQUE (ASSIGNMENT_ID, STUDENT_ID),
    CONSTRAINT CHK_ASUB_STATUS CHECK (STATUS IN ('SUBMITTED','LATE','GRADED'))
);

CREATE INDEX IDX_ASUB_ASSIGN  ON ASSIGNMENT_SUBMISSIONS(ASSIGNMENT_ID);
CREATE INDEX IDX_ASUB_STUDENT ON ASSIGNMENT_SUBMISSIONS(STUDENT_ID);
CREATE INDEX IDX_ASUB_STATUS  ON ASSIGNMENT_SUBMISSIONS(STATUS);

COMMENT ON TABLE  ASSIGNMENT_SUBMISSIONS IS '학생 과제 제출물 (과제 1건당 학생 1건)';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSIONS.STATUS IS 'SUBMITTED=정상제출, LATE=지각제출, GRADED=채점완료';


-- ============================================================
-- 14. 시험 도메인
-- ============================================================

CREATE TABLE EXAMS (
    ID           NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COURSE_ID    NUMBER(19)    NOT NULL,
    PROFESSOR_ID NUMBER(19)    NOT NULL,
    EXAM_TYPE    VARCHAR2(20)  NOT NULL,
    -- MIDTERM | FINAL | QUIZ | MAKEUP | EXTRA
    TITLE        VARCHAR2(500) NOT NULL,
    EXAM_DATE    DATE          NOT NULL,
    START_TIME   TIMESTAMP WITH TIME ZONE NOT NULL,
    END_TIME     TIMESTAMP WITH TIME ZONE NOT NULL,
    ROOM         VARCHAR2(100),
    MAX_STUDENTS NUMBER(5,0),
    STATUS       VARCHAR2(20)  DEFAULT 'SCHEDULED' NOT NULL,
    -- SCHEDULED | ONGOING | COMPLETED | CANCELLED
    DESCRIPTION  VARCHAR2(1000),
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_EXAM_COURSE FOREIGN KEY (COURSE_ID)    REFERENCES COURSES(ID),
    CONSTRAINT FK_EXAM_PROF   FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSORS(ID),
    CONSTRAINT CHK_EXAM_TYPE   CHECK (EXAM_TYPE IN ('MIDTERM','FINAL','QUIZ','MAKEUP','EXTRA')),
    CONSTRAINT CHK_EXAM_STATUS CHECK (STATUS IN ('SCHEDULED','ONGOING','COMPLETED','CANCELLED'))
);

CREATE INDEX IDX_EXAM_COURSE ON EXAMS(COURSE_ID);
CREATE INDEX IDX_EXAM_DATE   ON EXAMS(EXAM_DATE);
CREATE INDEX IDX_EXAM_STATUS ON EXAMS(STATUS);

COMMENT ON TABLE  EXAMS IS '시험 일정 (강의별 등록)';
COMMENT ON COLUMN EXAMS.EXAM_TYPE IS 'MIDTERM=중간, FINAL=기말, QUIZ=쪽지, MAKEUP=재시험, EXTRA=추가';

-- --------------------------------------------------------

CREATE TABLE EXAM_REGISTRATIONS (
    ID            NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EXAM_ID       NUMBER(19)    NOT NULL,
    STUDENT_ID    NUMBER(19)    NOT NULL,
    STATUS        VARCHAR2(20)  DEFAULT 'REGISTERED' NOT NULL,
    -- REGISTERED | ATTENDED | ABSENT | EXEMPT
    IS_SPECIAL    NUMBER(1,0)   DEFAULT 0 NOT NULL CHECK (IS_SPECIAL IN (0,1)),
    -- 1=특별시험(재시험·추가시험) 신청, 0=일반 배정
    REASON        VARCHAR2(500),
    REGISTERED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ER_EXAM    FOREIGN KEY (EXAM_ID)    REFERENCES EXAMS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ER_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID),
    CONSTRAINT UK_ER_UNIQUE  UNIQUE (EXAM_ID, STUDENT_ID),
    CONSTRAINT CHK_ER_STATUS CHECK (STATUS IN ('REGISTERED','ATTENDED','ABSENT','EXEMPT'))
);

CREATE INDEX IDX_ER_EXAM    ON EXAM_REGISTRATIONS(EXAM_ID);
CREATE INDEX IDX_ER_STUDENT ON EXAM_REGISTRATIONS(STUDENT_ID);
CREATE INDEX IDX_ER_STATUS  ON EXAM_REGISTRATIONS(STATUS);

COMMENT ON TABLE  EXAM_REGISTRATIONS IS '시험 응시 등록 (일반 배정 + 특별시험 신청)';
COMMENT ON COLUMN EXAM_REGISTRATIONS.IS_SPECIAL IS '1=학생이 직접 신청한 특별시험, 0=교수/교직원이 배정';
COMMENT ON COLUMN EXAM_REGISTRATIONS.STATUS     IS 'REGISTERED=등록, ATTENDED=응시, ABSENT=결시, EXEMPT=면제';

-- --------------------------------------------------------

CREATE TABLE EXAM_SUPERVISORS (
    ID              NUMBER(19)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EXAM_ID         NUMBER(19)    NOT NULL,
    SUPERVISOR_ID   NUMBER(19)    NOT NULL,    -- USERS.ID (교수 또는 교직원)
    SUPERVISOR_ROLE VARCHAR2(20)  DEFAULT 'ASSISTANT' NOT NULL,
    -- MAIN(주감독) | ASSISTANT(보조감독)
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ES_EXAM       FOREIGN KEY (EXAM_ID)       REFERENCES EXAMS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ES_SUPERVISOR FOREIGN KEY (SUPERVISOR_ID) REFERENCES USERS(ID),
    CONSTRAINT UK_ES_UNIQUE     UNIQUE (EXAM_ID, SUPERVISOR_ID),
    CONSTRAINT CHK_ES_ROLE      CHECK (SUPERVISOR_ROLE IN ('MAIN','ASSISTANT'))
);

CREATE INDEX IDX_ES_EXAM       ON EXAM_SUPERVISORS(EXAM_ID);
CREATE INDEX IDX_ES_SUPERVISOR ON EXAM_SUPERVISORS(SUPERVISOR_ID);

COMMENT ON TABLE  EXAM_SUPERVISORS IS '시험 감독관 배정 (주감독 1명 + 보조 복수)';
COMMENT ON COLUMN EXAM_SUPERVISORS.SUPERVISOR_ROLE IS 'MAIN=주감독, ASSISTANT=보조감독';
